server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

